src/Entity/Usuarios.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * Usuarios
 *
 * @ORM\Table(name="usuarios", uniqueConstraints={@ORM\UniqueConstraint(name="email", columns={"email"})}, indexes={@ORM\Index(name="suscripcion", columns={"suscripcion"})})
 * @ORM\Entity(repositoryClass="App\Repository\UsuariosRepository")
 * @UniqueEntity(
 *          fields={"email"},
 *          message="email.usuario.duplicado",
 *          errorPath="email",
 * 
 * )
 */
class Usuarios implements UserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id_usuario", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idUsuario;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=40, nullable=false)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=50, nullable=false)
     */
    private $nombre;

    /**
     * @var string
     *
     * @ORM\Column(name="apellido", type="string", length=50, nullable=false)
     */
    private $apellido;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=20, nullable=false)
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="dni", type="string", length=50, nullable=false)
     */
    private $dni;

    /**
     * @var int
     *
     * @ORM\Column(name="creditos", type="integer", nullable=false)
     */
    private $creditos = '2';

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="fecha_registro", type="date", nullable=true)
     */
    private $fechaRegistro;

    /**
     * @var \Suscripciones
     *
     * @ORM\ManyToOne(targetEntity="Suscripciones")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="suscripcion", referencedColumnName="nombre")
     * })
     */
    private $suscripcion;

    /**
     * @ORM\OneToMany(targetEntity="Subastas", mappedBy="idUsuario")
     */
    private $subastas;

    /**
     * @ORM\OneToMany(targetEntity="SemanasReserva", mappedBy="idUsuario")
     */
    private $reservas;

    public function __construct()
    {
        $this->subastas = new ArrayCollection();
        $this->reservas = new ArrayCollection();
    }

    public function getIdUsuario(): ?int
    {
        return $this->idUsuario;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->apellido;
    }

    public function setApellido(string $apellido): self
    {
        $this->apellido = $apellido;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getDni(): ?string
    {
        return $this->dni;
    }

    public function setDni(string $dni): self
    {
        $this->dni = $dni;

        return $this;
    }

    public function getCreditos(): ?int
    {
        return $this->creditos;
    }

    public function setCreditos(int $creditos): self
    {
        $this->creditos = $creditos;

        return $this;
    }

    public function getFechaRegistro(): ?\DateTimeInterface
    {
        return $this->fechaRegistro;
    }

    public function setFechaRegistro(?\DateTimeInterface $fechaRegistro): self
    {
        $this->fechaRegistro = $fechaRegistro;

        return $this;
    }

    public function getSuscripcion(): ?Suscripciones
    {
        return $this->suscripcion;
    }

    public function setSuscripcion(?Suscripciones $suscripcion): self
    {
        $this->suscripcion = $suscripcion;

        return $this;
    }

    public function restarCredito(){
        $this->creditos -= 1 ;
        return $this->creditos;
    }

    /**
     * @return Collection|Subastas[]
     */
    public function getSubastas(): Collection
    {
        return $this->subastas;
    }

    public function addSubasta(Subastas $subasta): self
    {
        if (!$this->subastas->contains($subasta)) {
            array_push($subastas, $subasta);
            //$this->subastas[] = $subasta;
            $subasta->setIdUsuario($this);
        }

        return $this;
    }

    public function removeSubasta(Subastas $subasta): self
    {
        if ($this->subastas->contains($subasta)) {
            $this->subastas->removeElement($subasta);
            // set the owning side to null (unless already changed)
            if ($subasta->getIdUsuario() === $this) {
                $subasta->setIdUsuario(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|SemanasReserva[]
     */
    public function getReservas(): Collection
    {
        return $this->reservas;
    }

    public function addReserva(SemanasReserva $reserva): self
    {
        if (!$this->reservas->contains($reserva)) {
            array_push($reservas, $reserva);
            //$this->reservas[] = $reserva;
            $reserva->setIdResidencia($this);
        }

        return $this;
    }

    public function removeReserva(SemanasReserva $reserva): self
    {
        if ($this->reservas->contains($reserva)) {
            $this->reservas->removeElement($reserva);
            // set the owning side to null (unless already changed)
            if ($reserva->getIdResidencia() === $this) {
                $reserva->setIdResidencia(null);
            }
        }

        return $this;
    }





    public function getSalt()
    {
        // podrías necesitar un verdadero salt dependiendo del encoder
        // ver la sección salt debajo
        return null;
    }

    public function getRoles()
    {
        return array('ROLE_USER');
    }
    public function eraseCredentials()
    {
    }
    public function getUsername()
    {
       // return $this->username;
    }


    public function getNumeroTarjeta(){

    }
}

src/Controller/UsuariosController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Entity;

use App\Entity\Usuarios;
use App\Entity\Tarjetas;
use App\Entity\Suscripciones;
use App\Entity\SemanasReserva;
use App\Entity\Pujas;
use App\Entity\Notificaciones;

use App\Form\TarjetasType;
use App\Form\UsuariosType;
use App\Form\TarjetasType2;


class UsuariosController extends AbstractController
{

    /**
    * @Route("/usuarios/perfil", name="miPerfil")
    */
    
    public function perfil(){
        $usuario = $this->getUser();
        /*if($this->isGranted('ROLE_ADMIN')){
            $usuario = $usuario->getIdUsuario();
        }*/
        
        $id = $usuario->getIdUsuario(); 
        $em = $this-> getDoctrine()->getManager();
        $tarjeta = $em->getRepository(Tarjetas::class)->findOneBy(['idUsuario' => $id]);
        if($this->isGranted('ROLE_ADMIN')){
        $vencimiento = strtotime( '+1 year' , strtotime( $usuario->getIdUsuario()->getFechaRegistro()->format('Y-m-d')));
        }
        else{
        $vencimiento = $usuario->getFechaRegistro()->add(date_interval_create_from_date_string('1 years'));
        }

        return $this->render('/usuarios/perfil.html.twig', ['usuario' => $usuario, 'tarjeta' => $tarjeta, 'vencimiento' => $vencimiento]);
    }
    /**
     * @Route("ver_perfil_de_{idUsuario}", name="ver_perfil_de_un_usuario")
     */
    public function verPerfilDe(int $idUsuario): Response{
        $usuario = $this->getDoctrine()->getManager()->getRepository(Usuarios::class)->findOneBy(['idUsuario' => $idUsuario]);
        $em = $this-> getDoctrine()->getManager();
        $tarjeta = $em->getRepository(Tarjetas::class)->findOneBy(['idUsuario' => $usuario->getIdUsuario()]);

        return $this->render("/usuarios/verPerfilDe.html.twig", ['usuario' => $usuario, 'tarjeta' => $tarjeta]);
    }

    /**
     * @Route("/usuarios/notificaciones", name="notificaciones")
     */
    public function notificaciones(){

        $usuario = $this->getUser();
        if($usuario != null){
            $notificaciones = $this->getDoctrine()->getManager()->getRepository(Notificaciones::class)->findBy(['idUsuario' => $usuario->getIdUsuario()]);

            $notificaciones = array_reverse($notificaciones);
            return $this->render("/usuarios/notificaciones.html.twig", ['notificaciones' => $notificaciones]);
        }
        else{
            return $this->render('/login/inicie_sesion.html.twig');
        }
    }


    /**
     * @Route("/usuarios/registrarsePaso1", name="registrarse_paso1")
     */
    public function mayorDeEdad(Request $request){

        return $this->render("/usuarios/mayoriaDeEdad.html.twig");
    }

    /**
     * @Route("/usuarios/registrarsePaso2", name="registrarse_paso2")
     */
    public function registrarse(Request $request): Response{

        $tarjeta = new Tarjetas();
        $form = $this->createForm(TarjetasType::class, $tarjeta);
        $form->handleRequest($request);
        

        if ($form->isSubmitted() && $form->isValid()) {
            //ver vencimiento  
            $tarjeta = $form->getData();
            $emailNuevo = $form->getData()->getIdUsuario()->getEmail();

                $entityManager = $this->getDoctrine()->getManager();
                $tarjeta->getIdUsuario()->setSuscripcion($this->getDoctrine()->getManager()->getRepository(Suscripciones::class)->findOneBy(['nombre' => 'standard']));
                $tarjeta->getIdUsuario()->setFechaRegistro(date_create(date('Y-m-d')));
                $entityManager->persist($tarjeta->getIDUsuario());
                
                $entityManager->persist($tarjeta);
                $entityManager->flush();
                
                $this->addFlash('success', 'Ya estás registrado en nuestra plataforma. Por favor, inicia sesión');
                return $this->redirectToRoute('inicio');
            
        }

        return $this->render('/usuarios/registrarse.html.twig', [
            'tarjeta' => $tarjeta,
            'form' => $form->createView(),
        ]);


    }

    /**
     * @var string
     */
    private $emailInvalido;

    /**
     * @Route("/usuarios/edit", name="usuario_edit",  methods={"GET","POST"})
     */
    public function editarUsuario(Request $request): Response{

        $emailInvalido = 'false';

        $usuario = $this->getUser();

        if($this->isGranted('ROLE_ADMIN')){
            $usuario = $usuario->getIdUsuario();
        }
        $emailLogeado = $usuario->getEmail();

        if($usuario != null){
            $form = $this->createForm(UsuariosType::class, $usuario);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $emailNuevo = $form->getData()->getEmail();
                if($emailNuevo != $emailLogeado){
                    if($this->getDoctrine()->getManager()->getRepository(Usuarios::class)->findBy(['email' => $emailNuevo]) == null){
                        $this->getDoctrine()->getManager()->flush();

                        return $this->redirectToRoute('miPerfil');
                    }
                    else{
                        $emailInvalido = 'true';
                        //$this->addFlash('danger', 'Email ya existente en el sistema. Modificación fallida.');
                        //return $this->redirectToRoute('miPerfil');
                    }
                }
                if($emailNuevo == $emailLogeado){
                        $this->getDoctrine()->getManager()->flush();

                        return $this->redirectToRoute('miPerfil');
                }
                
            }
            if($emailInvalido == 'true'){
                $this->addFlash('danger', 'Email ya existente en el sistema. Modificación fallida.');
                return $this->redirectToRoute('usuario_edit');
            }
            return $this->render('/usuarios/edit.html.twig', [
                'usuario' => $usuario,
                'form' => $form->createView(),
            ]); 
        }
        else{
            //
            return $this->render('/login/inicie_sesion.html.twig');
        }
    }


    /**
     * @Route("/usuarios/listado", name="usuarios_listado")
     */
    public function listado(Request $request){

        $usuarios = $this->getDoctrine()->getManager()->getRepository(Usuarios::class)->findAll();

        ksort($usuarios);
        $usuarios = array_reverse($usuarios);

        return $this->render("/usuarios/listado.html.twig", ['usuarios' => $usuarios]);
    }

    /**
     * @Route("/usuarios/cambiarSuscripcion/{usuario_email}", name="cambiar_suscripcion", methods={"GET"})
     * 
     */

    public function cambiarSuscripcion(string $usuario_email): Response{
            $usuario = $this->getDoctrine()->getManager()->getRepository(Usuarios::class)->findOneBy(['email' => $usuario_email]);
            if ($usuario->getSuscripcion()->getNombre() == 'standard'){
                $usuario->setSuscripcion( $this->getDoctrine()->getManager()->getRepository(Suscripciones::class)->findOneBy(['nombre' => 'premium']));
            }
            else{
                $usuario->setSuscripcion( $this->getDoctrine()->getManager()->getRepository(Suscripciones::class)->findOneBy(['nombre' => 'standard']));
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->flush();

            $this -> addFlash('succes','Has cambiado la suscripción del usuario exitosamente');
            return $this->redirectToRoute('ver_perfil_de_un_usuario', ["idUsuario" => $usuario->getIdUsuario()]);
    }

    /**
     * @Route("/usuarios/misReservas", name="mis_reservas")
     */
    public function misReservas(){
         $usuario = $this->getUser();

         if($this->isGranted('ROLE_ADMIN')){
            $usuario = $usuario->getIdUsuario();
        }

         $reservas = $this->getDoctrine()->getManager()->getRepository(SemanasReserva::class)->findBy(['idUsuario' => $usuario->getIdUsuario()]);

         $reservas = array_reverse($reservas);
         return $this->render("/usuarios/misReservas.html.twig", ['reservas' => $reservas]);
    }

    /**
     * @Route("/usuarios/reservasDe/{idUsuario}", name="ver_reservas_de_un_usuario", methods={"GET"})
     */
    public function verReservasDe(Usuarios $idUsuario){

        $reservas = $this->getDoctrine()->getManager()->getRepository(SemanasReserva::class)->findBy(['idUsuario' => $idUsuario->getIdUsuario()]);

        return $this->render("/usuarios/reservasDe.html.twig", ['reservas' => $reservas, 'usuario' =>$idUsuario]);
    }

    /**
     * @Route("/usuarios/subastasDe{idUsuario}", name="ver_subastas_de_un_usuario", methods={"GET"})
     */
    public function verSubastasDe(Usuarios $idUsuario){
        
        $coleccion = Array();
        $pujas = $this-> getDoctrine()->getManager()->getRepository(Pujas::class)->findBy(['idUsuario' => $idUsuario]);
        if($pujas){
            for ($i = 0; $i < sizeOf($pujas); $i++){
                $subastaDePuja = $pujas[$i]->getIdSubasta();
                if($subastaDePuja->getFinalizada() != 1 && !( in_array($subastaDePuja, $coleccion ) ) ){

templates/usuarios/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar informacion de usuario{% endblock %}

{% block bodyTitle %}
    <h1>
        Editar informacion del perfil
    </h1>
    <h6 class="font-weight-light">Ingresa los datos que queres modificar:</h6>
{% endblock %}



{% block body %}

{% if is_granted('IS_AUTHENTICATED_FULLY') %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

<div class="container text-center">
    
        <div class="row justify-content-center">
            
            <div class="col-md-6 border  " id="user-data-form"> 
                <h3>Mis datos:</h3>
                <br>
                {{ form_start(form) }}
                {{form_row(form.DNI)}}
                {{form_row(form.nombre)}}
                {{form_row(form.apellido)}}
                {{form_row(form.email)}}
                {{form_row(form.password)}}
                
            </div>
            
        </div>
        <br><br>

        <div class="row justify-content-center">
            <div class="col-sm-6">
                <a href="{{ path('miPerfil') }}" class="btn btn-lg btn-danger">Cancelar</a>

            </div>
            <div class="col-sm-6">
                <button type="submit" class="btn btn-lg btn-success">Guardar</button>

            </div>
        </div>
        {{ form_end(form) }}


</div>

{% endif %}
{% endblock %}

templates/usuarios/listado.html.twig
{% extends 'base.html.twig' %}
{% block title %}Usuarios{% endblock %}

{% block bodyTitle %}
    <h1>Usuarios del sistema</h1>
{% endblock %}

{% block body %}
    <div align="center" class="container">
     {% if usuarios %}
        <table class="table table-hover table-responsive-lg">
            <thead class="thead-dark">
                <tr>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Email</th>
                    <th>Fecha de registro</th>
                    <th>Suscripción</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in usuarios %}
                    <tr>
                        <td>{{ usuario.getNombre() }}</td>
                        <td> {{ usuario.getApellido() }} </td>
                        <td> {{ usuario.getEmail() }} </td>
                        <td>{{ usuario.getFechaRegistro().format('Y-m-d') }}</td>
                        <td> {{ usuario.getSuscripcion().getNombre() }} </td>
                        <td>
                            {% if app.user.getIdUsuario.getEmail == usuario.getEmail() %}
                                <a href="/usuarios/perfil" class="btn btn-warning">Ver Mi Perfil</a>
                            {% else %}
                                <a href="{{ path('ver_perfil_de_un_usuario', {'idUsuario': (usuario.getIdUsuario())}) }}" class="btn btn-info">Ver su Perfil</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
        {% else %}
            <p>El sistema aún no tiene usuarios</p>
        {% endif %}
{% endblock %}

templates/usuarios/mayoriaDeEdad.html.twig
{% block title %}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <div class="container" align="center">
            </br></br>
            <p>Tu usuario no tiene acceso a esta pagina. Ya has iniciado en la plataforma.</p>
            {% if is_granted("ROLE_ADMIN") %}
                <a class="nav-link" href="/logout">Cerrar la de sesión {{ app.user.getIdUsuario().getEmail() }}</a>
            {% else %}
                <a class="nav-link" href="/logout">Cerrar la de sesión {{ app.user.getEmail() }} </a>
            {% endif %}
            <a class="nav-link" href="/filtro">Ir a Home</a>
        </div>
    {% endif %}
{% endblock %}
{% block body %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="/css/base.css">

{% if not is_granted('IS_AUTHENTICATED_FULLY') %}


<div align="center"  class="container">
    </br></br>
    <h2 align="center">Paso 1</h2>
    <h1 align="center">Para registrarte en la plataforma de Home Switch Home, necesitás tener 18 años o más</h1>
    </br></br>
    <p>¿Sos mayor de edad?</p>
        <a href="{{ path('registrarse_paso2')}}" class="btn btn-lg btn-success">Sí</a>
        <a href="{{ path('inicio')}}" class="btn btn-lg btn-danger">No</a>

        </div>

{% endif %}
{% endblock %}

templates/usuarios/misReservas.html.twig
{% extends 'base.html.twig' %}
{% block title %}Mis reservas{% endblock %}

{% block bodyTitle %}
    <h1>Mis Reservas</h1>
{% endblock %}

{% block body %}
    
     {% if reservas %}
     <div align="center" class="container">
        <table class="table table-hover table-responsive-lg">
            <thead class="thead-dark">
                <tr>
                    <th></th>
                    <th>Residencia</th>
                    <th>Semana</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for reserva in reservas %}
                    <tr>
                        <td style="width:20%;heigth:30%">
                            <img src="{{reserva.getIdResidencia.fotos[0].ruta}}" class="img-fluid border border-primary" alt="Imagen residencia">
                    </td>
                        <td>{{ reserva.getIdResidencia().getNombre() }}</td>
                        <td>
                            <strong> <font color='Blue'>
                                {{ reserva.getFechaInicio().format('Y-m-d') }} / {{ reserva.getFechaFin().format('Y-m-d') }}</font>
                            </p>
                        </td>
                        <td><a href="{{ path('residencias_show', {'idResidencia': reserva.idResidencia().getIdResidencia()}) }}" class="btn btn-info">Ver Residencia</a>
                        
                        
                       {% if (reserva.fechaInicio.format('Y/m/d') > ("now" |date("Y/m/d"))) %}
                        <td><a href="{{ path('cancelar_reserva', {'idSemana': reserva.idSemana}) }}" class="btn btn-info">Cancelar Reserva</a>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <p>No hay reservas para mostrar</p>
    {% endif %}


{% endblock %}

templates/usuarios/modificarTarjeta.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cambiar forma de pago{% endblock %}

{% block bodyTitle %}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <h1>Cambiar forma de pago</h1>
    <h6 class="font-weight-light">Ingresa los datos que queres modificar:</h6>
    {% else  %}
        <h1>Tu usuario no tiene acceso a esta pagina.</h1>
    {% endif %}
{% endblock %}


{% block body %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% if is_granted('IS_AUTHENTICATED_FULLY') %}

<div class="container text-center">
    
    <div class="row justify-content-center">
        <div class="col-sm-5" id="card-data-form">
            <h3>Datos de la tarjeta:</h3>
            <br>
            {{ form_start(form) }}
            {{ form_row(form.numeroTarjeta) }}
            {{ form_row(form.codigo) }}
            {{ form_row(form.vencimiento) }}
            
        </div>
    </div>
    <br>
    <br>
    
    <div class="row justify-content-center">
        <div class="col-sm-4">
            <a href="{{ path('miPerfil') }}" class="btn btn-lg btn-danger">Cancelar</a>
            
        </div>
        <div class="col-sm-4">
                {{ form_row(form.save) }}
            
        </div>
    </div>
    {{ form_end(form) }}

{% else %}
    <div align="center" class="container">
        </br></br> </br></br></br>
        <p>No ha iniciado sesión</p>
        <a href="/inicio" class="btn btn-info">Iniciar sesión</a>
    </div>
{% endif %}
{% endblock %}

templates/usuarios/registrarse.html.twig
{% block title %}
    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <div class="container" align="center">
            </br></br>
            <p>Tu usuario no tiene acceso a esta pagina. Ya has iniciado en la plataforma.</p>
            {% if is_granted("ROLE_ADMIN") %}
                <a class="nav-link" href="/logout">Cerrar la de sesión {{ app.user.getIdUsuario().getEmail() }}</a>
            {% else %}
                <a class="nav-link" href="/logout">Cerrar la de sesión {{ app.user.getEmail() }} </a>
            {% endif %}
            <a class="nav-link" href="/filtro">Ir a Home</a>
        </div>
    {% endif %}
{% endblock %}
{% block body %}

{% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}

        {% for message in app.flashes('danger') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="/css/base.css">

{% if not is_granted('IS_AUTHENTICATED_FULLY') %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

<h2 align="center">Paso 2</h2>
<h1 align="center">Ingresa tus datos y los de tu tarjeta:</h1>
<div class="container text-center">
    </br></br>
    
    {{ form_start(form) }}
        <div class="row justify-content-between">
            <div class="col-md-6" id="user-data-form">
                <h3>{{form_label(form.idUsuario)}}</h3>
                <br>
                {{form_widget(form.idUsuario)}}
            </div>
            <br>
            <div class="col-md-4" id="card-data-form">
                <h3>Información de pago: </h3>
                <br>
                {{form_row(form.numeroTarjeta)}}
                {{form_row(form.codigo)}}
                {{form_row(form.vencimiento)}}
            </div>
        </div>
        
        <br><br>
        <div class="text-right">
                {{form_row(form.save)}}
        </div>
        {{form_end(form)}}
        </div>

{% endif %}
{% endblock %}